// Generated by CoffeeScript 1.11.1
(function() {
  var INITIAL_ANNOTATION_SIZE, LONG_TAP_DELAY,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  LONG_TAP_DELAY = 500;

  INITIAL_ANNOTATION_SIZE = 75;

  Annotator.Plugin.Touch.PDF = (function(superClass) {
    extend(PDF, superClass);

    function PDF(annotator) {
      this.annotator = annotator;
      this.pdfPlugin = this.annotator.plugins.PDF;
      this.pdfPlugin.viewerElement.addEventListener('pagerendered', (function(_this) {
        return function(event) {
          var annotationLayer, pageNumber, pageView;
          pageNumber = event.detail.pageNumber;
          pageView = _this.pdfPlugin.pdfPages[pageNumber - 1];
          annotationLayer = _this.pdfPlugin.annotationLayers[pageNumber - 1];
          return _this.listenForPDFTouchAnnotationCreation(pageNumber, pageView, annotationLayer);
        };
      })(this));
    }

    PDF.prototype.listenForPDFTouchAnnotationCreation = function(pageNumber, pageView, annotationLayer) {
      var timeout;
      timeout = null;
      return $(annotationLayer).on('touchstart touchmove touchend', (function(_this) {
        return function(event) {
          if (event.type === 'touchstart') {
            timeout = setTimeout(function() {
              var coordinates, rect, touch;
              timeout = null;
              rect = annotationLayer.getBoundingClientRect();
              touch = event.originalEvent.changedTouches[0];
              coordinates = {
                x: touch.clientX - rect.x,
                y: touch.clientY - rect.y
              };
              return _this.createNewPDFTouchHighlight(pageNumber, pageView, annotationLayer, coordinates);
            }, LONG_TAP_DELAY);
          }
          if (event.type === 'touchmove') {
            clearTimeout(timeout);
          }
          if (event.type === 'touchend' && timeout) {
            return clearTimeout(timeout);
          }
        };
      })(this));
    };

    PDF.prototype.createNewPDFTouchHighlight = function(pageNumber, pageView, annotationLayer, coordinates) {
      var initialLowerRight, initialUpperLeft;
      console.log('creating new highlight at page ' + pageNumber + ', (' + coordinates.x + ', ' + coordinates.y + ')');
      initialUpperLeft = {
        x: coordinates.x - INITIAL_ANNOTATION_SIZE / 2,
        y: coordinates.y - INITIAL_ANNOTATION_SIZE / 2
      };
      initialLowerRight = {
        x: coordinates.x + INITIAL_ANNOTATION_SIZE / 2,
        y: coordinates.y + INITIAL_ANNOTATION_SIZE / 2
      };
      this.pdfPlugin.createNewHighlight(annotationLayer, initialUpperLeft);
      return this.pdfPlugin.updateHighlightDimensions(initialLowerRight, initialUpperLeft);
    };

    return PDF;

  })(Annotator.Delegator);

}).call(this);
