// Generated by CoffeeScript 1.11.1
(function() {
  var INITIAL_ANNOTATION_SIZE, LONG_TAP_DELAY,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  LONG_TAP_DELAY = 500;

  INITIAL_ANNOTATION_SIZE = 75;

  Annotator.Plugin.Touch.PDF = (function(superClass) {
    extend(PDF, superClass);

    function PDF(annotator) {
      this.annotator = annotator;
      this.PDF = this.annotator.plugins.PDF;
      this.Touch = this.annotator.plugins.Touch;
      this.PDF.viewerElement.addEventListener('pagerendered', (function(_this) {
        return function(event) {
          var annotationLayer, pageNumber, pageView;
          pageNumber = event.detail.pageNumber;
          pageView = _this.PDF.pdfPages[pageNumber - 1];
          annotationLayer = _this.PDF.annotationLayers[pageNumber - 1];
          return _this.listenForLongTaps(pageNumber, pageView, annotationLayer);
        };
      })(this));
    }

    PDF.prototype.listenForLongTaps = function(pageNumber, pageView, annotationLayer) {
      var timeout;
      timeout = null;
      return $(annotationLayer).on('touchstart touchmove touchend', (function(_this) {
        return function(event) {
          if (!_this.PDF.editing && !_this.PDF.$newHighlightElement) {
            if (event.type === 'touchstart') {
              timeout = setTimeout(function() {
                var coordinates, rect, touch;
                timeout = null;
                rect = annotationLayer.getBoundingClientRect();
                touch = event.originalEvent.changedTouches[0];
                coordinates = {
                  x: touch.clientX - rect.x,
                  y: touch.clientY - rect.y
                };
                return _this.createNewHighlight(pageNumber, pageView, annotationLayer, coordinates);
              }, LONG_TAP_DELAY);
            }
            if (event.type === 'touchmove') {
              clearTimeout(timeout);
            }
            if (event.type === 'touchend' && timeout) {
              return clearTimeout(timeout);
            }
          }
        };
      })(this));
    };

    PDF.prototype.createNewHighlight = function(pageNumber, pageView, annotationLayer, coordinates) {
      var $bottomLeftHandle, $bottomRightHandle, $topLeftHandle, $topRightHandle, bottomRight, getHandleDragHandler, topLeft;
      topLeft = {
        x: coordinates.x - INITIAL_ANNOTATION_SIZE / 2,
        y: coordinates.y - INITIAL_ANNOTATION_SIZE / 2
      };
      bottomRight = {
        x: coordinates.x + INITIAL_ANNOTATION_SIZE / 2,
        y: coordinates.y + INITIAL_ANNOTATION_SIZE / 2
      };
      this.PDF.createNewHighlight(annotationLayer, topLeft);
      this.PDF.updateHighlight(topLeft, bottomRight);
      this.Touch.adder.removeAttr('disabled');
      this.Touch.adder.bind('tap', (function(event) {
        return event.stopPropagation();
      }), (function(_this) {
        return function() {
          _this.Touch.adder.attr('disabled', '');
          return _this.PDF.finalizeHighlight(pageNumber, pageView, topLeft, bottomRight);
        };
      })(this));
      getHandleDragHandler = (function(_this) {
        return function(top, left, bottom, right) {
          return function(event) {
            var rect, touch;
            event.preventDefault();
            rect = annotationLayer.getBoundingClientRect();
            touch = event.originalEvent.changedTouches[0];
            if (left) {
              topLeft.x = touch.clientX - rect.x;
            }
            if (top) {
              topLeft.y = touch.clientY - rect.y;
            }
            if (right) {
              bottomRight.x = touch.clientX - rect.x;
            }
            if (bottom) {
              bottomRight.y = touch.clientY - rect.y;
            }
            return _this.PDF.updateHighlight(topLeft, bottomRight);
          };
        };
      })(this);
      $topLeftHandle = $('<div class="pdf-highlight-handle top-left"></div>').on('touchmove', getHandleDragHandler(true, true, false, false));
      $topRightHandle = $('<div class="pdf-highlight-handle top-right"></div>').on('touchmove', getHandleDragHandler(true, false, false, true));
      $bottomLeftHandle = $('<div class="pdf-highlight-handle bottom-left"></div>').on('touchmove', getHandleDragHandler(false, true, true, false));
      $bottomRightHandle = $('<div class="pdf-highlight-handle bottom-right"></div>').on('touchmove', getHandleDragHandler(false, false, true, true));
      return this.PDF.$newHighlightElement.append($topLeftHandle, $topRightHandle, $bottomLeftHandle, $bottomRightHandle);
    };

    return PDF;

  })(Annotator.Delegator);

}).call(this);
