<?php
/**
 * @file
 *
 * Allow book marking of Page Turner pages
 *
 * Mike Widner <mikewidner@stanford.edu>
 *
 **/

define("PAGE_TURNER_BOOKMARK_FLAG", 'page_turner_bookmark'); // for consistency

/**
 * Implements hook_menu().
 */
function page_turner_bookmarks_menu() {
  $items = array();

  $items['admin/user-interface/page-turner/bookmark/add'] = array(
    'page callback' => 'page_turner_bookmarks_add',
    'access arguments' => array('flag page_turner_bookmark'),
    'type' => MENU_CALLBACK,
    );
  $items['admin/user-interface/page-turner/bookmark/remove'] = array(
    'page callback' => 'page_turner_bookmarks_remove',
    'access arguments' => array('unflag page_turner_bookmark'),
    'type' => MENU_CALLBACK,
    );
  return $items;
}

/*
 * Return bookmark page ranges for current node
 */
function page_turner_bookmarks_get_bookmarks($node) {
	global $user;
	$bookmarks = array();
	$flag = flag_get_user_flags('node', $node->nid);
	if (isset($flag[PAGE_TURNER_BOOKMARK_FLAG])) {
		$flagging_wrapper = entity_metadata_wrapper('flagging', $flag[PAGE_TURNER_BOOKMARK_FLAG]->flagging_id);
		foreach ($flagging_wrapper->field_bookmark_page as $page) {
			$bookmarks[] = $page->value();
		}
	}
	return $bookmarks;
}

/**
 * Parse _POST, Return array of page range and node context
 */
function page_turner_bookmarks_parse_query() {
	$page = $_POST['page'];
	settype($page, 'integer');
	return array(
		$page,
		menu_get_object($type = 'node', $position = 1, drupal_lookup_path('source', $_POST['path']))
	);
}


/**
 * Return true if given page has been bookmarked
 */
function page_turner_bookmarks_page_marked($wrapper, $page, &$delta = NULL) {
	// Update $delta in passing for cases where we need that information
	// and don't want to loop again
	foreach ($wrapper->field_bookmark_page->getIterator() as $delta => $bookmarked_page) {
		if ($page == $bookmarked_page->value()) {
			return TRUE;
		}
	}
	return FALSE;
}
/**
 * Menu callback
 *
 * Creates a new bookmark for the selected page(s)
 **/
function page_turner_bookmarks_add() {
	list($page, $node) = page_turner_bookmarks_parse_query();
	$bookmark_flag = flag_get_flag(PAGE_TURNER_BOOKMARK_FLAG);
	$flag = flag_get_user_flags('node', $node->nid);

	// TODO: Add exception handling, return success/failure as JSON
	// try { } catch (EntityMetadataWrapperException $exc) {

	if (isset($flag[PAGE_TURNER_BOOKMARK_FLAG])) {
		$flagging_wrapper = entity_metadata_wrapper('flagging', $flag[PAGE_TURNER_BOOKMARK_FLAG]->flagging_id);
	} else {
		$values = array(
			'flag_name' => PAGE_TURNER_BOOKMARK_FLAG,
			'fid' => $bookmark_flag->fid,
			'entity_type' => 'node',
			'entity_id' => $node->nid,
		);
		$flagging = entity_create('flagging', $values);
		$flagging_wrapper = entity_metadata_wrapper('flagging', $flagging);
	}

	if (!page_turner_bookmarks_page_marked($flagging_wrapper, $page)) {
		// Avoid duplicate bookmarks; probably impossible because of client-side state
		$flagging_wrapper->field_bookmark_page[] = $page;
		if (!isset($flagging)) {
			// Update an existing bookmark flagging, but prevent duplicates
			$flagging_wrapper->save();
		} else {
			// Save a new bookmark flag
			$bookmark_flag->flag('flag', $node->nid, NULL, FALSE, $flagging);
		}
	}
}

/**
 * Menu callback
 *
 * Removes existing bookmark for the selected page(s)
 **/
function page_turner_bookmarks_remove() {
	list($page, $node) = page_turner_bookmarks_parse_query();
	$flag = flag_get_user_flags('node', $node->nid);

	if (isset($flag[PAGE_TURNER_BOOKMARK_FLAG])) {
		$flagging_wrapper = entity_metadata_wrapper('flagging', $flag[PAGE_TURNER_BOOKMARK_FLAG]->flagging_id);
		$delta = NULL;
		if (page_turner_bookmarks_page_marked($flagging_wrapper, $page, $delta)) {
			// Match found, delete it
			$flagging_wrapper->field_bookmark_page[$delta] = NULL;
			$flagging_wrapper->save();

			if ($flagging_wrapper->field_bookmark_page->count() == 0) {
				// Bookmark is now empty, unflag the node
				$bookmark_flag = flag_get_flag(PAGE_TURNER_BOOKMARK_FLAG);
				$bookmark_flag->flag('unflag', $node->nid);
			}
			drupal_json_output('TRUE');
		}
	}
	drupal_json_output('FALSE');
	drupal_exit();
}

/**
 * Implements hook_node_view()
 */
function page_turner_bookmarks_node_view($node, $view_mode, $langcode) {
	drupal_add_js(array('page_turner_bookmarks' => page_turner_bookmarks_get_bookmarks($node)), 'setting');
	drupal_add_js(drupal_get_path('module', 'page_turner_bookmarks') . '/js/page_turner_bookmarks.js', array('group' => 'page_turner', 'weight' => 10));
}