// Generated by CoffeeScript 1.11.1
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Annotator.Plugin.Controls = (function(superClass) {
    extend(Controls, superClass);

    function Controls() {
      this.updateViewer = bind(this.updateViewer, this);
      return Controls.__super__.constructor.apply(this, arguments);
    }

    Controls.prototype.pluginInit = function() {
      if (!Annotator.supported()) {
        return;
      }
      return this.annotator.viewer.addField({
        load: this.updateViewer
      });
    };

    Controls.prototype.updateViewer = function(field, annotation, controls) {
      if ((annotation.permissions != null)) {
        if (!annotation.permissions.edit) {
          controls.hideEdit();
        }
        if (!annotation.permissions.del) {
          controls.hideDelete();
        }
      }
      return jQuery(field).remove();
    };

    return Controls;

  })(Annotator.Plugin);

}).call(this);
