// Generated by CoffeeScript 1.10.0
(function() {
  var $,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  $ = jQuery;

  Annotator.Plugin.Loading = (function(superClass) {
    extend(Loading, superClass);

    function Loading(element) {
      this.element = element;
    }

    Loading.prototype.pluginInit = function() {
      var spinnerElement;
      if (!Annotator.supported()) {
        return;
      }
      spinnerElement = this.setupElement();
      $(this.element).prepend(spinnerElement);
      return this.annotator.subscribe('annotationsLoaded', function() {
        return spinnerElement.remove();
      });
    };

    Loading.prototype.setupElement = function() {
      var elementHTML, spinnerElement;
      elementHTML = "<span id=\"annotations-loading\">\n    <i class=\"fa fa-spinner fa-pulse\"></i>\n    <span>Loading annotations...</span>\n</span>";
      return spinnerElement = $(elementHTML);
    };

    return Loading;

  })(Annotator.Plugin);

}).call(this);
