// Generated by CoffeeScript 1.10.0
(function() {
  var $,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  $ = jQuery;

  Annotator.Plugin.Loading = (function(superClass) {
    extend(Loading, superClass);

    function Loading() {
      return Loading.__super__.constructor.apply(this, arguments);
    }

    Loading.prototype.pluginInit = function() {
      if (!Annotator.supported()) {
        return;
      }
      return console.log('hey there from the plugin!');
    };

    return Loading;

  })(Annotator.Plugin);

}).call(this);
