// Generated by CoffeeScript 1.8.0
var $,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

$ = jQuery;

Annotator.Plugin.Privacy = (function(_super) {
  __extends(Privacy, _super);

  function Privacy() {
    this.updateViewer = __bind(this.updateViewer, this);
    return Privacy.__super__.constructor.apply(this, arguments);
  }

  Privacy.prototype.events = {
    'annotationViewerShown': "updateViewer"
  };

  Privacy.prototype.updateViewer = function(event, annotations) {
    var annotation, privacyStr, toAppend;
    annotation = annotations[0];
    if (annotation.permissions["read"].length > 0) {
      toAppend = " | Private";
    } else {
      toAppend = " | Public";
    }
    privacyStr = Annotator.Util.escape(toAppend);
    return $('.annotator-user').append(privacyStr);
  };

  return Privacy;

})(Annotator.Plugin);
