// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Annotator.Plugin.Replies = (function(superClass) {
    extend(Replies, superClass);

    function Replies() {
      this.cancelReply = bind(this.cancelReply, this);
      this.saveReply = bind(this.saveReply, this);
      this.drawReplies = bind(this.drawReplies, this);
      this.initReplies = bind(this.initReplies, this);
      this.addReplyLink = bind(this.addReplyLink, this);
      this.hideReplyArea = bind(this.hideReplyArea, this);
      this.addReplyArea = bind(this.addReplyArea, this);
      this.toggleVisibility = bind(this.toggleVisibility, this);
      this.hide = bind(this.hide, this);
      this.show = bind(this.show, this);
      return Replies.__super__.constructor.apply(this, arguments);
    }

    Replies.prototype.replyClasses = {
      "base": "annotator-reply",
      "hidden": "annotator-reply-hidden",
      "replyicon": "fa fa-reply",
      "reply": "annotator-reply-reply",
      "textarea": "annotator-reply-text",
      "button": "annotator-reply-button",
      "list": "annotator-reply-list"
    };

    Replies.prototype.replySelectors = {
      "replyarea": "div#content"
    };

    Replies.prototype.pluginInit = function() {
      if (!Annotator.supported()) {
        return;
      }
      return this.annotator.viewer.addField({
        load: this.initReplies
      });
    };

    Replies.prototype.show = function(field) {
      var textarea;
      field.classList.remove(this.replyClasses.hidden);
      field.style.display = "block";
      textarea = field.getElementsByTagName('textarea');
      if (textarea.length > 0) {
        return textarea[0].focus();
      }
    };

    Replies.prototype.hide = function(field) {
      field.classList.add(this.replyClasses.hidden);
      return field.style.display = "none";
    };

    Replies.prototype.toggleVisibility = function(field) {
      var ref;
      if (ref = this.replyClasses.hidden, indexOf.call(field.classList, ref) >= 0) {
        return this.show(field);
      } else {
        return this.hide(field);
      }
    };

    Replies.prototype.addReplyArea = function(annotation, pid) {
      var buttons, cancel, field, form, formid, save, textarea, textid;
      formid = this.replyClasses.base + "-form-" + annotation.id + "-" + pid;
      form = document.getElementById(formid);
      if (form != null) {
        return form;
      }
      form = document.createElement("form");
      form.id = formid;
      form.classList.add(this.replyClasses.base + "-form");
      textarea = document.createElement("textarea");
      textid = this.replyClasses.base + "-textarea-" + annotation.id + "-" + pid;
      textarea.id = textid;
      textarea.classList.add(this.replyClasses.textarea);
      buttons = document.createElement("div");
      buttons.classList.add(this.replyClasses.base + "-controls");
      save = document.createElement("a");
      save.classList.add(this.replyClasses.button);
      save.classList.add(this.replyClasses.base + "-save");
      save.innerHTML = "Save";
      save.addEventListener("click", (function(_this) {
        return function(event) {
          return _this.saveReply(event, annotation, textarea, pid);
        };
      })(this));
      cancel = document.createElement("a");
      cancel.classList.add(this.replyClasses.button);
      cancel.classList.add(this.replyClasses.base + "-cancel");
      cancel.innerHTML = "Cancel";
      cancel.addEventListener("click", (function(_this) {
        return function() {
          return _this.cancelReply(textarea);
        };
      })(this));
      buttons.appendChild(cancel);
      buttons.appendChild(save);
      form.appendChild(textarea);
      form.appendChild(buttons);
      field = document.querySelector(this.replySelectors.replyarea);
      field.appendChild(form);
      if (Annotator.Plugin.RichText != null) {
        CKEDITOR.replace(textid);
      }
      return form;
    };

    Replies.prototype.hideReplyArea = function(textarea) {
      return this.hide(textarea.parentNode);
    };

    Replies.prototype.addReplyLink = function(field, annotation, pid) {
      var className, i, len, ref, replyArea, span;
      if (pid == null) {
        pid = 0;
      }
      span = document.createElement("span");
      span.innerHTML = "Reply";
      ref = this.replyClasses.replyicon.split(" ");
      for (i = 0, len = ref.length; i < len; i++) {
        className = ref[i];
        span.classList.add(className);
      }
      replyArea = this.addReplyArea(annotation, pid);
      this.hide(replyArea);
      span.addEventListener("click", (function(_this) {
        return function() {
          return _this.toggleVisibility(replyArea);
        };
      })(this));
      return field.appendChild(span);
    };

    Replies.prototype.initReplies = function(field, annotation) {
      var n_replies, replies, replies_text, span;
      n_replies = Object.keys(annotation.comments).length;
      replies_text = "Replies";
      if (n_replies === 1) {
        replies_text = "Reply";
      }
      if (n_replies > 0) {
        span = document.createElement("span");
        span.innerHTML = n_replies + " " + replies_text;
        field.appendChild(span);
        replies = this.drawReplies(field, annotation);
        span.addEventListener("click", (function(_this) {
          return function() {
            return _this.toggleVisibility(replies);
          };
        })(this));
        this.hide(replies);
      }
      field.classList.add(this.replyClasses.base);
      return this.addReplyLink(field, annotation);
    };

    Replies.prototype.convertRepliesData = function(replies) {
      var data, date, date_string, id, repliesList, reply;
      repliesList = [];
      for (id in replies) {
        data = replies[id];
        date = new Date(data['created'] * 1000);
        date_string = date.getFullYear() + '-' + date.getMonth() + '-' + date.getDate() + ' ' + date.getHours() + ':' + date.getMinutes();
        reply = {
          'id': id,
          'pid': data['pid'],
          'text': data['comment_body']['und'][0]['safe_value'],
          'author': data['name'],
          'date': date_string,
          'thread': data['thread']
        };
        repliesList.push(reply);
      }
      return repliesList;
    };

    Replies.prototype.sortReplies = function(replies) {
      return replies.sort(function(a, b) {
        var thread_a, thread_b;
        thread_a = a['thread'].substring(0, -1);
        thread_b = b['thread'].substring(0, -1);
        if (thread_a < thread_b) {
          return -1;
        } else if (thread_a > thread_b) {
          return 1;
        } else {
          return 0;
        }
      });
    };

    Replies.prototype.replyDepth = function(thread) {
      return (thread.match(/\./g) || []).length;
    };

    Replies.prototype.initList = function(element) {
      var l;
      l = element.getElementsByTagName('ol');
      if (l.length === 0) {
        l = document.createElement('ol');
        l.classList.add(this.replyClasses.list);
        element.appendChild(l);
      } else {
        l = l[0];
      }
      return l;
    };

    Replies.prototype.getListAtDepth = function(element, depth) {
      var parent;
      parent = element;
      while (depth--) {
        parent = this.getListAtDepth(this.initList(parent), depth);
      }
      return parent;
    };

    Replies.prototype.drawReply = function(element, reply) {
      var li, text;
      li = document.createElement("li");
      li.innerHTML = reply['author'] + ' on ' + reply['date'];
      li.classList.add('annotator-reply-id-' + reply['id']);
      li.classList.add(this.replyClasses.reply);
      text = document.createElement("span");
      text.innerHTML = reply['text'];
      text.classList.add('annotator-reply-text');
      li.appendChild(text);
      element.appendChild(li);
      return li;
    };

    Replies.prototype.drawReplies = function(element, annotation) {
      var depth, el, i, len, li, list, replies, reply;
      replies = this.convertRepliesData(annotation.comments);
      replies = this.sortReplies(replies);
      list = this.initList(element);
      for (i = 0, len = replies.length; i < len; i++) {
        reply = replies[i];
        depth = this.replyDepth(reply['thread']);
        el = this.getListAtDepth(list, depth);
        li = this.drawReply(el, reply);
        this.addReplyLink(li, annotation, reply['id']);
      }
      return list;
    };

    Replies.prototype.saveReply = function(event, annotation, textarea, pid) {
      annotation.reply = {};
      annotation.reply.pid = pid;
      if (Annotator.Plugin.RichText != null) {
        annotation.reply.text = annotation.text = CKEDITOR.instances[textarea.id].getData();
      } else {
        annotation.reply.text = textarea.value;
      }
      annotation.reply.uid = Drupal.settings.annotator_replies.current_uid;
      this.annotator.publish('annotationUpdated', [annotation]);
      return this.hideReplyArea(textarea);
    };

    Replies.prototype.cancelReply = function(textarea) {
      textarea.value = "";
      return this.hideReplyArea(textarea);
    };

    return Replies;

  })(Annotator.Plugin);

}).call(this);
