// Generated by CoffeeScript 1.11.1
(function() {
  var $, editor_instance,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  $ = jQuery;

  editor_instance = 'annotator-field-0';

  Annotator.Plugin.RichText = (function(superClass) {
    extend(RichText, superClass);

    function RichText() {
      this.convertText = bind(this.convertText, this);
      this.updateText = bind(this.updateText, this);
      this.saveText = bind(this.saveText, this);
      return RichText.__super__.constructor.apply(this, arguments);
    }

    RichText.prototype.pluginInit = function() {
      var base, config, key;
      if (!Annotator.supported()) {
        return;
      }
      config = {
        extraPlugins: 'lineutils,embed,autoembed,image2',
        toolbar: [
          {
            name: 'paragraph',
            items: ['NumberedList', 'BulletedList']
          }, {
            name: 'links',
            items: ['Link', 'Unlink']
          }, {
            name: 'insert',
            items: ['embed, autoembed']
          }
        ],
        removePlugins: 'elementspath,font,resize',
        allowedContent: true,
        autoUpdateElement: true
      };
      key = Drupal.settings.annotator_richtext.iframely_api_key;
      if ((key != null ? key.length : void 0)) {
        base = '//iframe.ly/api/oembed?url={url}&callback={callback}&api_key=';
        config.embed_provider = base + key;
      }
      CKEDITOR.replace(editor_instance, config);
      this.annotator.subscribe('annotationEditorShown', (function(_this) {
        return function(Editor, annotation) {
          return _this.updateText(Editor, annotation);
        };
      })(this));
      this.annotator.subscribe('annotationEditorSubmit', (function(_this) {
        return function(Editor, annotation) {
          return _this.saveText(Editor, annotation);
        };
      })(this));
      return this.annotator.subscribe('annotationViewerShown', (function(_this) {
        return function(Viewer) {
          return _this.convertText(Viewer);
        };
      })(this));
    };

    RichText.prototype.saveText = function(Editor, annotation) {
      CKEDITOR.instances[editor_instance].updateElement();
      return annotation.text = CKEDITOR.instances[editor_instance].getData();
    };

    RichText.prototype.updateText = function(Editor, annotation) {
      return CKEDITOR.instances[editor_instance].setData(annotation.text);
    };

    RichText.prototype.convertText = function(Viewer) {
      var annotation, divList, index, ref, results;
      divList = $(Viewer.element[0]).find('span.annotator-controls, span.annotator-touch-controls').next();
      ref = Viewer.annotations;
      results = [];
      for (index in ref) {
        annotation = ref[index];
        if (annotation.text != null) {
          annotation.text = annotation.text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"');
          results.push(divList[index].innerHTML = annotation.text);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return RichText;

  })(Annotator.Plugin);

}).call(this);
