<?php
/**
 * @file
 * Code for the Lacuna Stories Views feature.
 */

/**
 * Implements of hook_views_data().
 */
function views_lacuna_stories_views_data() {
	return array(
		//Custom filter handler so that we can have author as an exposed filter select list (which then gets 'chosen-ed')
		'node' => array(
			'author_select' => array(
				'group' => t('Content'),
				'title' => t('Author (select list)'),
				'help' => t('Filter by author, choosing from dropdown list.'),
				'filter' => array('handler' => 'views_lacuna_stories_handler_filter_author_select'),
				'real field' => 'uid',
			)
		)
	);
}