# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/drude for more information and documentation.

version: "2"

services:
  # Web node
  web:
    hostname: web
    image: blinkreaction/drupal-apache:2.2-stable
    volumes:
      # Project root folder mapping
      - &project_root "../:/var/www"

  # DB node
  db:
    hostname: db
    image: blinkreaction/drupal-mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=drupal

  # CLI node
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: blinkreaction/drupal-cli:stable
    volumes:
      # Project root folder mapping
      - *project_root
      # PHP FPM configuration overrides
      - "./etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
      # PHP CLI configuration overrides
      - "./etc/php5/php-cli.ini:/etc/php5/cli/conf.d/z_php.ini"
      # Host home directory mapping (for SSH keys and ther credentials).
      # We try to map both options (b2d and Linux). The startup.sh script in cli container will decide which one to use.
      - /.home:/.home-b2d  # boot2docker-vagrant
      - ~/:/.home-linux   # Linux

  # Varnish node
  varnish:
    hostname: varnish
    image: blinkreaction/drupal-varnish:3.0-stable

  # Selenium node
  browser:
    hostname: browser
    image: selenium/standalone-chrome
