<?php
/**
 * @file
 * Supports workflows made up of arbitrary states.
 */

// The name of the Workfow form and function, to be used in various callbacks.
define('WORKFLOWFIELD_FORM', 'workflowfield_field_widget_form');

require_once dirname(__FILE__) . '/workflowfield.field.inc';
require_once dirname(__FILE__) . '/workflowfield.widget.inc';
require_once dirname(__FILE__) . '/workflowfield.formatter.inc';

/**
 * Implements hook_help().
 */
function workflowfield_help($path, $arg) {
  switch ($path) {
    case WORKFLOW_ADMIN_UI_PATH:
      return t('This page allows you to maintain Workflows. Once a workflow is
        created, you can maintain your entity type and add a Field of type
        \'Workflow\'.');
  }
}
